# Generated by Django 4.2.6 on 2024-02-02 07:49

import community_product.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community_product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="communityproduct",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("web_application", "Web application"),
                    ("mobile_application", "Mobile application"),
                    ("dashboard", "Dashboard"),
                    ("academic", "Academic work"),
                    ("machine_learning", "Machine Learning (ML) product"),
                    ("analytics", "Analytics"),
                    ("publications", "Publications"),
                ],
                default="web_application",
                max_length=18,
            ),
        ),
        migrations.AddField(
            model_name="communityproduct",
            name="product_year",
            field=models.PositiveIntegerField(
                default=community_product.models.get_current_year,
                validators=[django.core.validators.MaxValueValidator(3000)],
            ),
        ),
    ]
