# Generated by Django 4.2.6 on 2024-02-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community_product", "0002_communityproduct_product_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communityproduct",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("web_application", "Web application"),
                    ("mobile_application", "Mobile application"),
                    ("dashboard", "Dashboard"),
                    ("academic_publication", "Academic Publication"),
                    ("machine_learning", "Machine Learning (ML) product"),
                    ("analytics", "Analytics"),
                ],
                default="web_application",
                max_length=20,
            ),
        ),
    ]
