# Generated by Django 4.2.6 on 2024-02-05 01:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community_product", "0004_communityproduct_problem_statement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="communityproduct",
            name="problem_statement_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="communityproduct",
            name="problem_statement_ms",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="communityproduct",
            name="product_description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="communityproduct",
            name="product_description_ms",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="communityproduct",
            name="product_name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="communityproduct",
            name="product_name_ms",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="communityproduct",
            name="solutions_developed_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="communityproduct",
            name="solutions_developed_ms",
            field=models.TextField(null=True),
        ),
    ]
