# Generated by Django 4.2.6 on 2024-02-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community_product", "0006_communityproduct_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="communityproduct",
            name="date_approved",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
