# Generated by Django 4.2.6 on 2024-02-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community_product", "0007_communityproduct_date_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="communityproduct",
            name="thumbnail",
            field=models.ImageField(null=True, upload_to="community-products/"),
        ),
    ]
