# Generated by Django 4.2.6 on 2024-02-15 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community_product", "0008_communityproduct_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="communityproduct",
            name="date_rejected",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="communityproduct",
            name="remark",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="communityproduct",
            name="remark_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="communityproduct",
            name="remark_ms",
            field=models.TextField(blank=True, null=True),
        ),
    ]
