# Generated by Django 4.2.6 on 2024-02-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community_product", "0009_communityproduct_date_rejected_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communityproduct",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="community-products/"
            ),
        ),
    ]
