# Generated by Django 5.1.3 on 2025-09-10 01:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community_product", "0010_alter_communityproduct_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="communityproduct",
            name="thumbnail_s3",
            field=models.URLField(blank=True, null=True),
        ),
    ]
