# Generated by Django 5.1.3 on 2025-09-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community_product", "0011_communityproduct_thumbnail_s3"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communityproduct",
            name="thumbnail_s3",
            field=models.URLField(blank=True, null=True, verbose_name="Thumbnail S3"),
        ),
    ]
