# Generated by Django 4.1.7 on 2023-03-14 08:01

import django.contrib.postgres.indexes
from django.db import migrations, models
from django.contrib.postgres.operations import BtreeGinExtension


class Migration(migrations.Migration):

    dependencies = [
        ('data_gov_my', '0003_alter_namedashboard_firstname_first_name'),
    ]

    operations = [
        BtreeGinExtension(),
        migrations.AlterField(
            model_name='namedashboard_firstname',
            name='first_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AddIndex(
            model_name='namedashboard_firstname',
            index=django.contrib.postgres.indexes.GinIndex(fastupdate=True, fields=['first_name'], name='first_name_idx'),
        ),
    ]
