# Generated by Django 4.1.7 on 2023-03-16 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_gov_my', '0006_namedashboard_firstname_decade_0'),
    ]

    operations = [
        migrations.RenameField(
            model_name='namedashboard_firstname',
            old_name='decade_0',
            new_name='d_1920',
        ),
        migrations.RenameField(
            model_name='namedashboard_firstname',
            old_name='decade_10',
            new_name='d_1930',
        ),
        migrations.RenameField(
            model_name='namedashboard_firstname',
            old_name='decade_20',
            new_name='d_1940',
        ),
        migrations.RenameField(
            model_name='namedashboard_firstname',
            old_name='decade_30',
            new_name='d_1950',
        ),
        migrations.RenameField(
            model_name='namedashboard_firstname',
            old_name='decade_40',
            new_name='d_1960',
        ),
        migrations.RenameField(
            model_name='namedashboard_firstname',
            old_name='decade_50',
            new_name='d_1970',
        ),
        migrations.RenameField(
            model_name='namedashboard_firstname',
            old_name='decade_60',
            new_name='d_1980',
        ),
        migrations.RenameField(
            model_name='namedashboard_firstname',
            old_name='decade_70',
            new_name='d_1990',
        ),
        migrations.RenameField(
            model_name='namedashboard_firstname',
            old_name='decade_80',
            new_name='d_2000',
        ),
        migrations.RenameField(
            model_name='namedashboard_firstname',
            old_name='decade_90',
            new_name='d_2010',
        ),
    ]
