# Generated by Django 4.1.7 on 2023-03-16 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_gov_my', '0008_alter_namedashboard_firstname_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameDashboard_LastName',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('d_1920', models.IntegerField(default=0, null=True)),
                ('d_1930', models.IntegerField(default=0, null=True)),
                ('d_1940', models.IntegerField(default=0, null=True)),
                ('d_1950', models.IntegerField(default=0, null=True)),
                ('d_1960', models.IntegerField(default=0, null=True)),
                ('d_1970', models.IntegerField(default=0, null=True)),
                ('d_1980', models.IntegerField(default=0, null=True)),
                ('d_1990', models.IntegerField(default=0, null=True)),
                ('d_2000', models.IntegerField(default=0, null=True)),
                ('d_2010', models.IntegerField(default=0, null=True)),
                ('total', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
