# Generated by Django 4.1.7 on 2023-04-20 07:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0011_alter_i18njson_language"),
        ("data_gov_my", "0011_electiondashboard_candidates"),
    ]

    operations = []
