# Generated by Django 4.1.7 on 2023-05-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0018_rename_translation_json_i18njson_translation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="electiondashboard_seats",
            name="state",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
