# Generated by Django 4.1.7 on 2023-05-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_gov_my', '0021_alter_electiondashboard_candidates_voter_turnout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electiondashboard_candidates',
            name='voter_turnout_perc',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='electiondashboard_candidates',
            name='votes_rejected_perc',
            field=models.FloatField(default=None, null=True),
        ),
    ]
