# Generated by Django 4.1.7 on 2023-05-10 04:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "data_gov_my",
            "0022_alter_electiondashboard_candidates_voter_turnout_perc_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="i18njson",
            name="route",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
