# Generated by Django 4.1.7 on 2023-05-11 04:48

import collections
from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0023_alter_i18njson_route"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogjson",
            name="catalog_data",
            field=jsonfield.fields.JSONField(
                load_kwargs={"object_pairs_hook": collections.OrderedDict}
            ),
        ),
        migrations.AlterField(
            model_name="dashboardjson",
            name="chart_data",
            field=jsonfield.fields.JSONField(
                load_kwargs={"object_pairs_hook": collections.OrderedDict}
            ),
        ),
    ]
