# Generated by Django 4.1.7 on 2023-05-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0025_modsdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="modsdata",
            name="language",
            field=models.CharField(
                choices=[("en-GB", "English"), ("ms-MY", "Bahasa Melayu")],
                default="en-GB",
                max_length=5,
            ),
        ),
    ]
