# Generated by Django 4.1.7 on 2023-05-25 03:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0026_modsdata_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogjson",
            name="demographic",
            field=models.CharField(default="", max_length=300),
            preserve_default=False,
        ),
    ]
