# Generated by Django 4.1.7 on 2023-06-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0029_metajson_route"),
    ]

    operations = [
        migrations.AddField(
            model_name="electiondashboard_candidates",
            name="majority",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="electiondashboard_candidates",
            name="majority_perc",
            field=models.FloatField(default=None, null=True),
        ),
    ]
