# Generated by Django 4.1.7 on 2023-06-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0029_metajson_route"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="metajson",
            name="id",
        ),
        migrations.AlterField(
            model_name="metajson",
            name="dashboard_name",
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
