# Generated by Django 4.1.7 on 2023-06-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0030_electiondashboard_candidates_majority_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="electiondashboard_candidates",
            name="slug",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="electiondashboard_seats",
            name="slug",
            field=models.CharField(default="", max_length=100),
        ),
    ]
