# Generated by Django 4.1.7 on 2023-06-14 04:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0030_remove_metajson_id_alter_metajson_dashboard_name"),
        ("data_gov_my", "0032_electiondashboard_dropdown"),
    ]

    operations = []
