# Generated by Django 4.1.7 on 2023-06-20 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0033_merge_20230614_0444"),
    ]

    operations = [
        migrations.AddField(
            model_name="electiondashboard_seats",
            name="voter_turnout",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="electiondashboard_seats",
            name="voter_turnout_perc",
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="electiondashboard_seats",
            name="votes_rejected",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="electiondashboard_seats",
            name="votes_rejected_perc",
            field=models.FloatField(default=None, null=True),
        ),
    ]
