# Generated by Django 4.1.7 on 2023-07-20 06:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0037_rename_geographic_catalogjson_geography"),
    ]

    operations = [
        migrations.RenameField(
            model_name="catalogjson",
            old_name="demographic",
            new_name="demography",
        ),
    ]
