# Generated by Django 4.1.7 on 2023-08-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0040_alter_publication_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="publication_type",
            field=models.CharField(default="cpi", max_length=50),
            preserve_default=False,
        ),
    ]
