# Generated by Django 4.1.7 on 2023-08-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0041_publication_publication_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="publicationresource",
            options={"ordering": ["resource_id"]},
        ),
        migrations.AddField(
            model_name="publicationresource",
            name="resource_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="publicationresource",
            constraint=models.UniqueConstraint(
                fields=("resource_id", "publication"),
                name="unique publication resource by publication and id",
            ),
        ),
    ]
