# Generated by Django 4.1.7 on 2023-08-08 01:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0042_alter_publicationresource_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="publication",
            options={"ordering": ["-release_date", "publication_id"]},
        ),
    ]
