# Generated by Django 4.1.7 on 2023-08-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0043_alter_publication_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="publication_type_title",
            field=models.CharField(default="placeholder", max_length=100),
            preserve_default=False,
        ),
    ]
