# Generated by Django 4.1.7 on 2023-08-17 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0044_publication_publication_type_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicationDocumentation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("publication_id", models.CharField(max_length=30)),
                ("documentation_type", models.CharField(max_length=30)),
                (
                    "language",
                    models.CharField(
                        choices=[("en-GB", "English"), ("ms-MY", "Bahasa Melayu")],
                        default="en-GB",
                        max_length=5,
                    ),
                ),
                ("publication_type", models.CharField(max_length=50)),
                ("publication_type_title", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=300)),
                ("release_date", models.DateField()),
            ],
            options={
                "ordering": ["-release_date", "publication_id"],
            },
        ),
        migrations.AlterField(
            model_name="publicationresource",
            name="publication",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resources",
                to="data_gov_my.publication",
            ),
        ),
        migrations.CreateModel(
            name="PublicationDocumentationResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resource_id", models.IntegerField()),
                ("resource_type", models.CharField(max_length=50)),
                ("resource_name", models.CharField(max_length=100)),
                ("resource_link", models.URLField(max_length=150)),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="data_gov_my.publicationdocumentation",
                    ),
                ),
            ],
            options={
                "ordering": ["resource_id"],
            },
        ),
        migrations.AddIndex(
            model_name="publicationdocumentation",
            index=models.Index(
                fields=["publication_id", "language"], name="pub_docs_id_language_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="publicationdocumentation",
            constraint=models.UniqueConstraint(
                fields=("publication_id", "language"),
                name="unique publication documentation by language",
            ),
        ),
        migrations.AddConstraint(
            model_name="publicationdocumentationresource",
            constraint=models.UniqueConstraint(
                fields=("resource_id", "publication"),
                name="unique publication documentation resource by publication and id",
            ),
        ),
    ]
