# Generated by Django 4.1.7 on 2023-08-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0045_publicationdocumentation_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="publicationdocumentation",
            index=models.Index(
                fields=["documentation_type", "language"],
                name="pub_docs_type_language_idx",
            ),
        ),
    ]
