# Generated by Django 4.1.7 on 2023-08-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_gov_my', '0047_publicationupcoming_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthTable',
            fields=[
                ('key', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
