# Generated by Django 4.1.7 on 2023-08-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0049_alter_publication_publication_type_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicationupcoming",
            name="publication_id",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="publicationupcoming",
            name="publication_type",
            field=models.CharField(max_length=100),
        ),
    ]
