# Generated by Django 4.1.7 on 2023-08-20 08:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0050_alter_publicationupcoming_publication_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="publicationupcoming",
            options={"ordering": ["release_date", "publication_id"]},
        ),
    ]
