# Generated by Django 4.1.7 on 2023-08-21 04:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0048_authtable"),
        ("data_gov_my", "0051_alter_publicationupcoming_options"),
    ]

    operations = []
