# Generated by Django 4.1.7 on 2023-08-21 08:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0053_i18njson_sites_metajson_sites"),
    ]

    operations = [
        migrations.AlterField(
            model_name="i18njson",
            name="sites",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("datagovmy", "https://data.gov.my"),
                        ("kkmnow", "https://data.moh.gov.my/"),
                        ("opendosm", "https://open.dosm.gov.my/"),
                    ],
                    max_length=50,
                ),
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="metajson",
            name="sites",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("datagovmy", "https://data.gov.my"),
                        ("kkmnow", "https://data.moh.gov.my/"),
                        ("opendosm", "https://open.dosm.gov.my/"),
                    ],
                    max_length=50,
                ),
                default=list,
                size=None,
            ),
        ),
    ]
