# Generated by Django 4.1.7 on 2023-09-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0054_alter_i18njson_sites_alter_metajson_sites"),
    ]

    operations = [
        migrations.CreateModel(
            name="KTMBTimeseries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service", models.CharField(max_length=100)),
                ("origin", models.CharField(max_length=100)),
                ("destination", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("passengers", models.IntegerField()),
                ("frequency", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="KTMBTimeseriesCallout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service", models.CharField(max_length=100)),
                ("origin", models.CharField(max_length=100)),
                ("destination", models.CharField(max_length=100)),
                ("passengers", models.IntegerField()),
                ("frequency", models.CharField(max_length=50)),
            ],
        ),
    ]
