# Generated by Django 4.1.7 on 2023-09-04 03:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0054_alter_i18njson_sites_alter_metajson_sites"),
    ]

    operations = [
        migrations.RenameField(
            model_name="viewcount",
            old_name="all_time_view",
            new_name="view_count",
        ),
    ]
