# Generated by Django 4.1.7 on 2023-09-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0056_alter_ktmbtimeseries_passengers_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrasaranaTimeseries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service", models.CharField(max_length=100)),
                ("origin", models.CharField(max_length=100)),
                ("destination", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("passengers", models.IntegerField(null=True)),
                ("frequency", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="PrasaranaTimeseriesCallout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service", models.CharField(max_length=100)),
                ("origin", models.CharField(max_length=100)),
                ("destination", models.CharField(max_length=100)),
                ("passengers", models.IntegerField(null=True)),
                ("frequency", models.CharField(max_length=50)),
            ],
        ),
    ]
