# Generated by Django 4.1.7 on 2023-09-05 03:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0057_prasaranatimeseries_prasaranatimeseriescallout"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="ktmbtimeseries",
            index=models.Index(
                fields=["service", "origin", "destination"], name="ktmb_timeseries_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ktmbtimeseriescallout",
            index=models.Index(
                fields=["service", "origin", "destination"], name="ktmb_callout_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prasaranatimeseries",
            index=models.Index(
                fields=["service", "origin", "destination"],
                name="prasarana_timeseries_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="prasaranatimeseriescallout",
            index=models.Index(
                fields=["service", "origin", "destination"],
                name="prasarana_callout_idx",
            ),
        ),
    ]
