# Generated by Django 4.1.7 on 2023-09-07 07:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0055_rename_all_time_view_viewcount_view_count"),
        ("data_gov_my", "0058_ktmbtimeseries_ktmb_timeseries_idx_and_more"),
    ]

    operations = []
