# Generated by Django 4.1.7 on 2023-09-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0059_merge_20230907_0752"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogjson",
            name="exclude_openapi",
            field=models.BooleanField(default=False),
        ),
    ]
