# Generated by Django 4.1.7 on 2023-09-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0060_catalogjson_exclude_openapi"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicationresource",
            name="downloads",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
