# Generated by Django 4.1.7 on 2023-09-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0061_publicationresource_downloads"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicationdocumentationresource",
            name="downloads",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
