# Generated by Django 4.1.7 on 2023-09-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0061_publicationresource_downloads"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogjson",
            name="catalog_category_opendosm",
            field=models.CharField(default="", max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="catalogjson",
            name="catalog_category_opendosm_name",
            field=models.CharField(default="", max_length=600),
        ),
        migrations.AddField(
            model_name="catalogjson",
            name="catalog_subcategory_opendosm",
            field=models.CharField(default="", max_length=300),
        ),
        migrations.AddField(
            model_name="catalogjson",
            name="catalog_subcategory_opendosm_name",
            field=models.CharField(default="", max_length=600),
        ),
    ]
