# Generated by Django 4.1.7 on 2023-09-08 10:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0062_publicationdocumentationresource_downloads"),
        ("data_gov_my", "0063_alter_catalogjson_catalog_category_opendosm_and_more"),
    ]

    operations = []
