# Generated by Django 4.1.7 on 2023-09-12 17:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0064_merge_20230908_1043"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ElectionDashboard_Candidates",
        ),
        migrations.DeleteModel(
            name="ElectionDashboard_Dropdown",
        ),
        migrations.DeleteModel(
            name="ElectionDashboard_Party",
        ),
        migrations.DeleteModel(
            name="ElectionDashboard_Seats",
        ),
    ]
