# Generated by Django 4.1.7 on 2023-09-18 16:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0065_delete_electiondashboard_candidates_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="publication",
            options={},
        ),
        migrations.AlterModelOptions(
            name="publicationdocumentation",
            options={},
        ),
    ]
