# Generated by Django 4.1.7 on 2023-10-10 17:26

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0066_alter_publication_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogjson",
            name="dataviz",
            field=jsonfield.fields.JSONField(default={}),
            preserve_default=False,
        ),
    ]
