# Generated by Django 4.1.7 on 2023-10-11 16:40

import collections
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0067_catalogjson_dataviz"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogueJson",
            fields=[
                (
                    "id",
                    models.CharField(max_length=400, primary_key=True, serialize=False),
                ),
                ("exclude_openapi", models.BooleanField(default=False)),
                ("catalog_meta", models.JSONField()),
                ("catalog_name", models.CharField(max_length=400)),
                ("catalog_category", models.CharField(max_length=300)),
                ("catalog_category_name", models.CharField(default="", max_length=600)),
                ("catalog_subcategory", models.CharField(default="", max_length=300)),
                (
                    "catalog_subcategory_name",
                    models.CharField(default="", max_length=600),
                ),
                (
                    "catalog_category_opendosm",
                    models.CharField(max_length=300, null=True),
                ),
                (
                    "catalog_category_opendosm_name",
                    models.CharField(max_length=600, null=True),
                ),
                (
                    "catalog_subcategory_opendosm",
                    models.CharField(max_length=300, null=True),
                ),
                (
                    "catalog_subcategory_opendosm_name",
                    models.CharField(max_length=600, null=True),
                ),
                ("time_range", models.CharField(max_length=100)),
                ("geography", models.CharField(max_length=300)),
                ("demography", models.CharField(max_length=300)),
                ("dataset_begin", models.IntegerField(default=0)),
                ("dataset_end", models.IntegerField(default=0)),
                ("data_source", models.CharField(max_length=100)),
                (
                    "catalog_data",
                    jsonfield.fields.JSONField(
                        load_kwargs={"object_pairs_hook": collections.OrderedDict}
                    ),
                ),
                ("dataviz", jsonfield.fields.JSONField()),
                ("file_src", models.CharField(default="", max_length=400)),
            ],
        ),
    ]
