# Generated by Django 4.1.7 on 2023-11-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0069_cataloguejson_related_datasets"),
    ]

    operations = [
        migrations.AddField(
            model_name="cataloguejson",
            name="catalog_category_kkm",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="cataloguejson",
            name="catalog_category_kkm_name",
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name="cataloguejson",
            name="catalog_subcategory_kkm",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="cataloguejson",
            name="catalog_subcategory_kkm_name",
            field=models.CharField(max_length=600, null=True),
        ),
    ]
