# Generated by Django 4.1.7 on 2023-11-22 02:06

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0070_cataloguejson_catalog_category_kkm_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cataloguejson",
            name="dataviz",
            field=jsonfield.fields.JSONField(default=list),
        ),
    ]
