# Generated by Django 4.1.7 on 2023-12-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0071_alter_cataloguejson_dataviz"),
    ]

    operations = [
        migrations.AddField(
            model_name="explorersupdate",
            name="data_next_update",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
