# Generated by Django 4.1.7 on 2023-12-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0072_explorersupdate_data_next_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="explorersupdate",
            name="data_next_update",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
