# Generated by Django 4.1.7 on 2023-12-13 07:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0074_explorersmetajson"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="explorersupdate",
            name="data_next_update",
        ),
    ]
