# Generated by Django 4.1.7 on 2024-01-12 08:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0075_remove_explorersupdate_data_next_update"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CatalogJson",
        ),
        migrations.DeleteModel(
            name="CatalogueJson",
        ),
    ]
