# Generated by Django 4.2.6 on 2024-02-02 05:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0076_delete_catalogjson_delete_cataloguejson"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ViewCount",
        ),
    ]
