# Generated by Django 4.1.7 on 2024-04-30 08:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0078_car_carpopularitytimeseries"),
        ("data_gov_my", "0078_publicationsubscription"),
    ]

    operations = []
