# Generated by Django 4.1.7 on 2024-05-01 16:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0079_merge_20240430_1658"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ExplorersMetaJson",
        ),
    ]
