# Generated by Django 4.1.7 on 2024-05-01 16:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0080_delete_explorersmetajson"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExplorersMetaJson",
            fields=[
                (
                    "dashboard_name",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("dashboard_meta", models.JSONField()),
                ("route", models.CharField(max_length=100, null=True)),
                (
                    "sites",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("datagovmy", "https://data.gov.my"),
                                ("kkmnow", "https://data.moh.gov.my/"),
                                ("opendosm", "https://open.dosm.gov.my/"),
                                ("databnm", "https://bnm.data.gov.my/"),
                            ],
                            max_length=50,
                        ),
                        default=list,
                        size=None,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="i18njson",
            name="sites",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("datagovmy", "https://data.gov.my"),
                        ("kkmnow", "https://data.moh.gov.my/"),
                        ("opendosm", "https://open.dosm.gov.my/"),
                        ("databnm", "https://bnm.data.gov.my/"),
                    ],
                    max_length=50,
                ),
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="metajson",
            name="sites",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("datagovmy", "https://data.gov.my"),
                        ("kkmnow", "https://data.moh.gov.my/"),
                        ("opendosm", "https://open.dosm.gov.my/"),
                        ("databnm", "https://bnm.data.gov.my/"),
                    ],
                    max_length=50,
                ),
                default=list,
                size=None,
            ),
        ),
    ]
