# Generated by Django 4.1.7 on 2024-05-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0081_explorersmetajson_alter_i18njson_sites_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarPopularityTimeseriesMaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("maker", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("cars", models.IntegerField(default=0, null=True)),
                ("cars_cumul", models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CarPopularityTimeseriesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("maker", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("cars", models.IntegerField(default=0, null=True)),
                ("cars_cumul", models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="carpopularitytimeseries",
            name="car",
        ),
        migrations.DeleteModel(
            name="Car",
        ),
        migrations.DeleteModel(
            name="CarPopularityTimeseries",
        ),
        migrations.AddIndex(
            model_name="carpopularitytimeseriesmodel",
            index=models.Index(
                fields=["maker", "model", "date"], name="car_popularity_model_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carpopularitytimeseriesmaker",
            index=models.Index(
                fields=["maker", "date"], name="car_popularity_maker_idx"
            ),
        ),
    ]
