# Generated by Django 4.1.7 on 2024-05-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0082_carpopularitytimeseriesmaker_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="carpopularitytimeseriesmaker",
            name="car_popularity_maker_idx",
        ),
        migrations.RemoveIndex(
            model_name="carpopularitytimeseriesmodel",
            name="car_popularity_model_idx",
        ),
        migrations.AddIndex(
            model_name="carpopularitytimeseriesmaker",
            index=models.Index(fields=["maker"], name="car_popularity_maker_idx"),
        ),
        migrations.AddIndex(
            model_name="carpopularitytimeseriesmodel",
            index=models.Index(
                fields=["maker", "model"], name="car_popularity_model_idx"
            ),
        ),
    ]
