# Generated by Django 4.1.7 on 2024-05-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "data_gov_my",
            "0083_remove_carpopularitytimeseriesmaker_car_popularity_maker_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("maker", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("maker_model", models.CharField(max_length=200)),
            ],
        ),
    ]
