# Generated by Django 4.1.7 on 2024-10-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "data_gov_my",
            "0085_publicationsubtype_publicationtype_subscription_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicationsubtype",
            name="subtype_bm",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="publicationsubtype",
            name="subtype_en",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="publicationtype",
            name="type_bm",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="publicationtype",
            name="type_en",
            field=models.CharField(max_length=100),
        ),
    ]
