# Generated by Django 4.1.7 on 2024-11-04 02:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0086_alter_publicationsubtype_subtype_bm_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="id",
        ),
        migrations.AlterField(
            model_name="subscription",
            name="email",
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
