# Generated by Django 4.1.7 on 2024-11-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0088_subscription_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="language",
            field=models.CharField(
                choices=[("en-GB", "English"), ("ms-MY", "Bahasa Melayu")],
                default="en-GB",
                max_length=5,
            ),
        ),
    ]
