# Generated by Django 4.1.7 on 2024-11-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0089_subscription_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicationtype",
            name="dict_bm",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="publicationtype",
            name="dict_en",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="publicationtype",
            name="language",
            field=models.CharField(
                choices=[("en-GB", "English"), ("ms-MY", "Bahasa Melayu")],
                max_length=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="publicationtype",
            name="type_bm",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="publicationtype",
            name="type_en",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
