# Generated by Django 4.1.7 on 2024-11-14 19:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "data_gov_my",
            "0090_publicationtype_dict_bm_publicationtype_dict_en_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publicationtype",
            name="language",
        ),
    ]
