# Generated by Django 4.1.7 on 2024-11-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0091_remove_publicationtype_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicationsubtype",
            name="order",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="publicationtype",
            name="order",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
