# Generated by Django 4.1.7 on 2024-11-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0092_publicationsubtype_order_publicationtype_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicationsubtype",
            name="id",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="publicationtype",
            name="id",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="publicationtype",
            name="type_bm",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="publicationtype",
            name="type_en",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
