# Generated by Django 4.1.7 on 2024-11-17 10:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0094_alter_publicationsubtype_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="publicationsubtype",
            options={"ordering": ["publication_type", "order"]},
        ),
        migrations.RemoveField(
            model_name="publicationtype",
            name="dict_bm",
        ),
        migrations.RemoveField(
            model_name="publicationtype",
            name="dict_en",
        ),
    ]
