# Generated by Django 4.1.7 on 2024-11-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_gov_my", "0095_alter_publicationsubtype_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="description_email",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
