# Generated by Django 4.1.7 on 2024-01-17 03:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit", models.CharField(max_length=255, null=True)),
                ("namaBangunan", models.CharField(max_length=255, null=True)),
                ("poBox", models.FloatField(blank=True, null=True)),
                ("namaJalan", models.CharField(max_length=255)),
                ("lokaliti", models.CharField(max_length=255)),
                ("poskod", models.CharField(max_length=5)),
                ("bandar", models.CharField(max_length=255)),
                ("negeri", models.CharField(max_length=255)),
                ("negara", models.CharField(max_length=255)),
                ("latitud1", models.FloatField()),
                ("longitud1", models.FloatField()),
                ("postcode", models.CharField(max_length=8)),
            ],
        ),
        migrations.AddIndex(
            model_name="address",
            index=models.Index(
                fields=["postcode"], name="address_add_postcod_507e2f_idx"
            ),
        ),
    ]
