# Generated by Django 4.1.7 on 2024-01-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0002_alter_address_pobox"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="combined_address",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
