# Generated by Django 4.1.7 on 2024-01-17 05:24

from django.db import migrations

from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0003_address_combined_address"),
    ]

    operations = [
        TrigramExtension(),
    ]
