# Generated by Django 4.1.7 on 2024-01-18 15:43

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0005_address_address_add_combine_fa4d70_gin"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="address",
            name="address_add_combine_fa4d70_gin",
        ),
        migrations.RenameField(
            model_name="address",
            old_name="combined_address",
            new_name="address",
        ),
        migrations.RenameField(
            model_name="address",
            old_name="lokaliti",
            new_name="locality",
        ),
        migrations.RemoveField(
            model_name="address",
            name="bandar",
        ),
        migrations.RemoveField(
            model_name="address",
            name="latitud1",
        ),
        migrations.RemoveField(
            model_name="address",
            name="longitud1",
        ),
        migrations.RemoveField(
            model_name="address",
            name="namaBangunan",
        ),
        migrations.RemoveField(
            model_name="address",
            name="namaJalan",
        ),
        migrations.RemoveField(
            model_name="address",
            name="negara",
        ),
        migrations.RemoveField(
            model_name="address",
            name="negeri",
        ),
        migrations.RemoveField(
            model_name="address",
            name="poBox",
        ),
        migrations.RemoveField(
            model_name="address",
            name="poskod",
        ),
        migrations.RemoveField(
            model_name="address",
            name="unit",
        ),
        migrations.AddField(
            model_name="address",
            name="district",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="address",
            name="dun",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="address",
            name="lat",
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="address",
            name="lon",
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="address",
            name="parlimen",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="address",
            name="subdistrict",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="address",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["address"], name="address_add_address_06136e_gin"
            ),
        ),
    ]
