# Generated by Django 4.1.7 on 2024-01-18 15:43

from django.db import migrations
from django.contrib.postgres.operations import BtreeGinExtension


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0006_remove_address_address_add_combine_fa4d70_gin_and_more"),
    ]

    operations = [
        BtreeGinExtension(),
    ]
