# Generated by Django 4.1.7 on 2024-09-19 10:38

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    """
    This is a squashed migration file, it was generated bcs of the issue in `fix/gin-migration-op`
    branch making `0007_address_custom_btree_migration` migration file to have no operations. Here
    is what should be happening next (TODO):
        1. Need to make sure all next deployment will apply this migration
        2. Have another PR to:
            a. Delete all `replaces` files
            b. Updated migration dependencies to point to this instead
            c. Remove `replaces` variable
    """

    replaces = [
        ("address", "0007_address_custom_btree_migration"),
        ("address", "0008_remove_address_address_add_address_06136e_gin_and_more"),
    ]

    dependencies = [
        ("address", "0006_remove_address_address_add_combine_fa4d70_gin_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="address",
            name="address_add_address_06136e_gin",
        ),
        migrations.AddIndex(
            model_name="address",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["address"], name="address_gin_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
