# Generated by Django 4.1.7 on 2024-01-22 01:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0008_remove_address_address_add_address_06136e_gin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="state",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
