# Generated by Django 4.1.7 on 2023-12-21 03:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_request", "0006_datarequest_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="language",
            field=models.CharField(
                choices=[("en-GB", "English"), ("ms-MY", "Bahasa Melayu")],
                default="en-GB",
                max_length=5,
            ),
        ),
    ]
