# Generated by Django 4.1.7 on 2023-12-22 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("data_request", "0008_remove_datarequest_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agency",
            fields=[
                (
                    "acronym",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("name_en", models.CharField(max_length=255, null=True)),
                ("name_ms", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="datarequest",
            name="agency",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="data_request.agency",
            ),
        ),
    ]
