# Generated by Django 4.1.7 on 2023-12-22 07:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_request", "0009_agency_alter_datarequest_agency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datarequest",
            name="agency",
        ),
    ]
