# Generated by Django 4.1.7 on 2023-12-22 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("data_request", "0013_alter_datarequest_published_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datarequest",
            name="agency",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="data_request.agency",
            ),
        ),
    ]
