# Generated by Django 4.2.6 on 2024-02-21 05:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_request", "0014_alter_datarequest_agency"),
    ]

    operations = [
        migrations.AddField(
            model_name="agency",
            name="emails",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(max_length=254), default=[], size=None
            ),
            preserve_default=False,
        ),
    ]
