# Generated by Django 4.1.7 on 2025-09-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_request", "0017_datarequestadminemail"),
    ]

    operations = [
        migrations.AddField(
            model_name="datarequest",
            name="live_remark",
            field=models.TextField(blank=True, null=True),
        ),
    ]
