# Generated by Django 5.1.3 on 2025-09-10 01:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_request", "0018_datarequest_live_remark"),
    ]

    operations = [
        migrations.AddField(
            model_name="datarequest",
            name="live_remark_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="datarequest",
            name="live_remark_ms",
            field=models.TextField(blank=True, null=True),
        ),
    ]
