# Generated by Django 4.1.7 on 2023-12-11 17:38

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataCatalogue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="DataCatalogueMeta",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("exclude_openapi", models.BooleanField()),
                ("manual_trigger", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("title_en", models.CharField(max_length=255, null=True)),
                ("title_ms", models.CharField(max_length=255, null=True)),
                ("description", models.TextField()),
                ("description_en", models.TextField(null=True)),
                ("description_ms", models.TextField(null=True)),
                ("link_parquet", models.URLField()),
                ("link_csv", models.URLField()),
                ("link_preview", models.URLField()),
                ("frequency", models.CharField(max_length=50)),
                (
                    "geography",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=10),
                        size=None,
                    ),
                ),
                (
                    "demography",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=10),
                        size=None,
                    ),
                ),
                ("dataset_begin", models.PositiveIntegerField()),
                ("dataset_end", models.PositiveIntegerField()),
                (
                    "data_source",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=10),
                        size=None,
                    ),
                ),
                ("data_as_of", models.CharField(max_length=50)),
                ("last_updated", models.CharField(max_length=50, null=True)),
                ("next_update", models.CharField(max_length=50, null=True)),
                ("methodology", models.TextField()),
                ("methodology_en", models.TextField(null=True)),
                ("methodology_ms", models.TextField(null=True)),
                ("caveat", models.TextField()),
                ("caveat_en", models.TextField(null=True)),
                ("caveat_ms", models.TextField(null=True)),
                ("publication", models.TextField()),
                ("publication_en", models.TextField(null=True)),
                ("publication_ms", models.TextField(null=True)),
                (
                    "dataviz",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.JSONField(), size=None
                    ),
                ),
                ("translations", models.JSONField()),
                ("translations_en", models.JSONField(null=True)),
                ("translations_ms", models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Field",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("title_en", models.CharField(max_length=255, null=True)),
                ("title_ms", models.CharField(max_length=255, null=True)),
                ("description", models.TextField()),
                ("description_en", models.TextField(null=True)),
                ("description_ms", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="RelatedDataset",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=255)),
                ("title_en", models.CharField(max_length=255, null=True)),
                ("title_ms", models.CharField(max_length=255, null=True)),
                ("description", models.TextField()),
                ("description_en", models.TextField(null=True)),
                ("description_ms", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SiteCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site", models.CharField(max_length=10)),
                ("category", models.CharField(max_length=255)),
                ("category_en", models.CharField(max_length=255, null=True)),
                ("category_ms", models.CharField(max_length=255, null=True)),
                ("subcategory", models.CharField(max_length=255)),
                ("subcategory_en", models.CharField(max_length=255, null=True)),
                ("subcategory_ms", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="sitecategory",
            constraint=models.UniqueConstraint(
                fields=("site", "category", "subcategory"), name="unique_sitecategory"
            ),
        ),
        migrations.AddConstraint(
            model_name="field",
            constraint=models.UniqueConstraint(
                fields=("name", "title", "description"), name="unique_field"
            ),
        ),
        migrations.AddField(
            model_name="datacataloguemeta",
            name="fields",
            field=models.ManyToManyField(to="data_catalogue.field"),
        ),
        migrations.AddField(
            model_name="datacataloguemeta",
            name="related_datasets",
            field=models.ManyToManyField(to="data_catalogue.relateddataset"),
        ),
        migrations.AddField(
            model_name="datacataloguemeta",
            name="site_category",
            field=models.ManyToManyField(to="data_catalogue.sitecategory"),
        ),
        migrations.AddField(
            model_name="datacatalogue",
            name="catalogue_meta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="data_catalogue.datacataloguemeta",
            ),
        ),
        migrations.AddIndex(
            model_name="datacatalogue",
            index=models.Index(fields=["id"], name="data_catalogue_idx"),
        ),
    ]
