# Generated by Django 4.1.7 on 2023-12-17 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("data_catalogue", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datacataloguemeta",
            name="dataviz",
        ),
        migrations.CreateModel(
            name="Dataviz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataviz_id", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("title_en", models.CharField(max_length=255, null=True)),
                ("title_ms", models.CharField(max_length=255, null=True)),
                ("chart_type", models.CharField(max_length=25)),
                ("config", models.JSONField()),
                (
                    "catalogue_meta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_catalogue.datacataloguemeta",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="dataviz",
            constraint=models.UniqueConstraint(
                fields=("catalogue_meta", "id"), name="unique_dataviz"
            ),
        ),
    ]
