# Generated by Django 4.1.7 on 2023-12-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_catalogue", "0002_remove_datacataloguemeta_dataviz_dataviz_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datacatalogue",
            name="slug",
            field=models.JSONField(default=dict),
        ),
    ]
