# Generated by Django 4.1.7 on 2023-12-18 03:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_catalogue", "0003_datacatalogue_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataviz",
            name="dropdown",
            field=models.JSONField(default=list),
        ),
    ]
