# Generated by Django 4.1.7 on 2023-12-18 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("data_request", "0002_datarequest_rejection_reason"),
        ("data_catalogue", "0004_dataviz_dropdown"),
    ]

    operations = [
        migrations.AddField(
            model_name="datacataloguemeta",
            name="data_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="data_request.datarequest",
            ),
        ),
    ]
