# Generated by Django 4.1.7 on 2023-12-19 02:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_catalogue", "0004_dataviz_dropdown"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datacataloguemeta",
            name="link_csv",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="datacataloguemeta",
            name="link_parquet",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="datacataloguemeta",
            name="link_preview",
            field=models.URLField(null=True),
        ),
    ]
