# Generated by Django 4.1.7 on 2023-12-19 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("data_request", "0002_datarequest_rejection_reason"),
        ("data_catalogue", "0005_alter_datacataloguemeta_link_csv_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datacataloguemeta",
            name="data_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="datacatalogue_set",
                to="data_request.datarequest",
            ),
        ),
    ]
