# Generated by Django 4.1.7 on 2023-12-22 07:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_catalogue", "0007_alter_datacataloguemeta_data_request"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datacataloguemeta",
            name="data_request",
        ),
    ]
