# Generated by Django 4.1.7 on 2024-01-09 07:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_catalogue", "0008_remove_datacataloguemeta_data_request"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="field",
            name="unique_field",
        ),
    ]
