# Generated by Django 4.1.7 on 2024-01-09 08:41

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("data_catalogue", "0009_remove_field_unique_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datacatalogue",
            name="data",
            field=jsonfield.fields.JSONField(),
        ),
    ]
