# Generated by Django 4.1.7 on 2024-01-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_catalogue", "0010_alter_datacatalogue_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="field",
            options={"ordering": ["index"]},
        ),
        migrations.AddField(
            model_name="field",
            name="index",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
