# Generated by Django 4.1.7 on 2024-01-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_catalogue", "0011_alter_field_options_field_index"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="datacatalogue",
            options={"ordering": ["index"]},
        ),
        migrations.AddField(
            model_name="datacatalogue",
            name="index",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
