# Generated by Django 4.2.6 on 2024-01-30 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_catalogue", "0012_alter_datacatalogue_options_datacatalogue_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="datacataloguemeta",
            name="title_sort",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="sitecategory",
            name="category_sort",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="sitecategory",
            name="subcategory_sort",
            field=models.IntegerField(null=True),
        ),
    ]
