# Generated by Django 4.2.6 on 2024-02-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_catalogue", "0013_datacataloguemeta_title_sort_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datacataloguemeta",
            name="size_csv",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="datacataloguemeta",
            name="size_parquet",
            field=models.URLField(null=True),
        ),
    ]
