# Generated by Django 4.1.7 on 2024-08-01 03:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_catalogue", "0014_datacataloguemeta_size_csv_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datacataloguemeta",
            name="link_editions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=10),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
