# Generated by Django 4.1.7 on 2024-09-13 06:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_catalogue", "0015_datacataloguemeta_link_editions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datacataloguemeta",
            name="data_source",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=20), size=None
            ),
        ),
    ]
